# Generated by Django 5.1 on 2024-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="contact",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
