# Generated by Django 5.1 on 2024-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_botuser_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
