# Generated by Django 5.1 on 2024-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_botuser_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botuser",
            name="name",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
