# Generated by Django 5.1 on 2024-08-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_botuser_name_alter_botuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botuser",
            name="code",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="botuser",
            name="contact",
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
