# Generated by Django 5.1 on 2024-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_botuser_code_alter_botuser_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botuser",
            name="code",
            field=models.CharField(max_length=7, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="contact",
            field=models.CharField(max_length=15, verbose_name="Contact"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Telegram Name"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="user_id",
            field=models.CharField(max_length=15, verbose_name="User ID"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="Username"
            ),
        ),
    ]
